# Generated by Django 5.1.7 on 2025-03-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('user', '0002_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderid',
            name='user_sender_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sender_id', to='user.senderid'),
        ),
    ]
