# Generated by Django 5.1.7 on 2025-03-21 16:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Le Sender ID ne doit contenir que des lettres et des chiffres', regex='^[A-Za-z0-9]+$')], verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par défaut')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_ids', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Sender ID',
                'verbose_name_plural': 'Sender IDs',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_sender_id_per_user')],
            },
        ),
    ]
