# Generated by Django 5.1.7 on 2025-04-01 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_senderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde de crédits SMS disponibles', max_digits=10, verbose_name='Crédits SMS'),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Achat'), ('USAGE', 'Utilisation'), ('REFUND', 'Remboursement')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('payment_method', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Carte de crédit'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money')], max_length=20, null=True, verbose_name='Méthode de paiement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True, verbose_name='Référence')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Complétée'), ('FAILED', 'Échouée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction de crédits',
                'verbose_name_plural': 'Transactions de crédits',
                'ordering': ['-created_at'],
            },
        ),
    ]
