# Generated by Django 5.1.7 on 2025-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_credits_credittransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code promo unique', max_length=50, unique=True, verbose_name='Code')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Pourcentage de réduction à appliquer', max_digits=5, verbose_name='Pourcentage de réduction')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le code promo est actif', verbose_name='Actif')),
                ('valid_from', models.DateTimeField(help_text='Date de début de validité', verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(help_text='Date de fin de validité', verbose_name="Valide jusqu'au")),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'utilisations (laissez vide pour illimité)", null=True, verbose_name='Utilisations maximales')),
                ('current_uses', models.PositiveIntegerField(default=0, help_text="Nombre d'utilisations actuelles", verbose_name='Utilisations actuelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
