# Generated by Django 5.1.7 on 2025-04-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_credittransaction_price_credittransaction_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone pour le paiement mobile', max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='pin',
            field=models.CharField(blank=True, help_text='Code PIN pour le paiement mobile', max_length=10, null=True, verbose_name='Code PIN'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='promo_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de réduction appliqué', max_digits=5, verbose_name='Réduction promo'),
        ),
    ]
